Exit correctly when command is misused

diff --git a/sshcommand b/sshcommand
--- a/sshcommand
+++ b/sshcommand
@@ -126,6 +126,11 @@ sshcommand-help() {
 }
 
 main() {
+  if [[ -z "$1" ]]; then
+    sshcommand-help
+    exit 1
+  fi
+
   case "$1" in
     create) # sshcommand create <user> <command>
       sshcommand-create "$@"
@@ -139,10 +144,13 @@ main() {
       sshcommand-acl-remove "$@"
       ;;
 
-    help|*) # sshcommand help
+    help) # sshcommand help
       sshcommand-help
       ;;
 
+    *)
+      log-fail "invalid command"
+      exit 1
   esac
 }
 
